---
# tasks file for docker
- name: Install Docker
  block:
    - name: Uninstall previous versions of Docker
      apt:
        name:
          - 'docker'
          - 'docker-engine'
          - 'docker.io'
          - 'containerd'
          - 'runc'
        state: absent
        update_cache: yes
    - name: Install required packages
      apt:
        name:
          - 'apt-transport-https'
          - 'ca-certificates'
          - 'curl'
          - 'gnupg-agent'
          - 'software-properties-common'
          - 'python-docker'
        state: latest
        update_cache: yes
      register: apt_res_install_docker_required
      retries: 3
      delay: 15
      until: apt_res_install_docker_required is success
    - name: Add Docker apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    - name: Add Docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
        filename: docker
        update_cache: yes
    - name: Install Docker
      apt:
        name:
          - 'docker-ce'
          - 'docker-ce-cli'
          - 'containerd.io'
        state: latest
        update_cache: yes
      register: apt_res_install_docker
      retries: 3
      delay: 15
      until: apt_res_install_docker is success


